# Generated by Django 4.0.3 on 2022-05-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_username_skill_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name_linkedin',
            new_name='social_linkedin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name_twitter',
            new_name='social_twitter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name_youtube',
            new_name='social_youtube',
        ),
    ]
