# Generated by Django 4.0.3 on 2022-05-25 06:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_name_linkedin_profile_social_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.TextField()),
                ('bool_read', models.BooleanField(default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='users.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
            options={
                'ordering': ['bool_read', 'date_created'],
            },
        ),
    ]
