# Generated by Django 4.0.3 on 2022-05-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message_body_alter_message_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='sender_name',
        ),
    ]
